package ch.admin.bit.jeap.jwe.web;

import ch.admin.bit.jeap.jwe.crypto.JweRsaKeys;
import ch.admin.bit.jeap.jwe.keymanagement.JweKeyStore;
import ch.admin.bit.jeap.jwe.test.JweTestKeys;
import com.nimbusds.jose.*;
import com.nimbusds.jose.crypto.DirectDecrypter;
import com.nimbusds.jose.crypto.RSAEncrypter;
import com.nimbusds.jose.jwk.RSAKey;
import jakarta.servlet.FilterChain;
import org.junit.jupiter.api.BeforeAll;
import org.junit.jupiter.api.Test;
import org.springframework.mock.web.MockHttpServletRequest;
import org.springframework.mock.web.MockHttpServletResponse;

import javax.crypto.KeyGenerator;
import javax.crypto.SecretKey;
import java.util.List;

import static java.nio.charset.StandardCharsets.US_ASCII;
import static java.nio.charset.StandardCharsets.UTF_8;
import static org.assertj.core.api.Assertions.assertThat;

/**
 * Verifies response encryption: the response is encrypted as a {@code dir}/A256GCM JWE using the CEK
 * the client supplied in the {@code JWE-Response-Key} envelope — for both GET and body methods — and
 * the client decrypts it with that response CEK (which is independent of the request CEK).
 */
class JweServletFilterResponseEncryptionTest {

    private static final String KID = "resp-filter-key:1";
    private static final String RESPONSE_BODY = "{\"status\":\"ok\"}";
    private static RSAKey key;
    private static JweKeyStore keyStore;

    @BeforeAll
    static void setUp() {
        key = JweRsaKeys.from(JweTestKeys.rsa4096(0), KID);
        keyStore = TestJweKeyStores.single(key);
    }

    private JweServletFilter filter() {
        return new JweServletFilter(
                new JweFilterPaths(List.of("/**"), List.of()),
                keyStore,
                new JweFilterSettings(List.of("application/json"), "JWE-Response-Key"));
    }

    private static SecretKey aes256() throws Exception {
        KeyGenerator generator = KeyGenerator.getInstance("AES");
        generator.init(256);
        return generator.generateKey();
    }

    private static final FilterChain JSON_CONTROLLER = (request, response) -> {
        response.setContentType("application/json");
        response.getOutputStream().write(RESPONSE_BODY.getBytes(UTF_8));
    };

    private static String decrypt(MockHttpServletResponse response, SecretKey cek) throws Exception {
        JWEObject parsed = JWEObject.parse(new String(response.getContentAsByteArray(), US_ASCII));
        parsed.decrypt(new DirectDecrypter(cek));
        return parsed.getPayload().toString();
    }

    private String responseKeyEnvelope(SecretKey responseCek) throws Exception {
        JWEObject envelope = new JWEObject(
                new JWEHeader.Builder(JWEAlgorithm.RSA_OAEP_256, EncryptionMethod.A256GCM).keyID(KID).build(),
                new Payload(responseCek.getEncoded()));
        envelope.encrypt(new RSAEncrypter(key.toRSAPublicKey()));
        return envelope.serialize();
    }

    @Test
    void postResponseEncryptedWithResponseKeyEnvelopeCek() throws Exception {
        // The request body has its own CEK (generated by Nimbus); the response uses the separate CEK
        // from the JWE-Response-Key header.
        JWEObject requestJwe = new JWEObject(
                new JWEHeader.Builder(JWEAlgorithm.RSA_OAEP_256, EncryptionMethod.A256GCM)
                        .keyID(KID).contentType("application/json").build(),
                new Payload("{\"order\":42}"));
        requestJwe.encrypt(new RSAEncrypter(key.toRSAPublicKey()));
        SecretKey responseCek = aes256();

        MockHttpServletRequest request = new MockHttpServletRequest("POST", "/api/orders");
        request.setContentType(JweProtocol.APPLICATION_JOSE_VALUE);
        request.addHeader("Accept", "application/jose");
        request.addHeader("JWE-Response-Key", responseKeyEnvelope(responseCek));
        request.setContent(requestJwe.serialize().getBytes(US_ASCII));
        MockHttpServletResponse response = new MockHttpServletResponse();

        filter().doFilter(request, response, JSON_CONTROLLER);

        assertThat(response.getContentType()).isEqualTo(JweProtocol.APPLICATION_JOSE_VALUE);
        assertThat(decrypt(response, responseCek)).isEqualTo(RESPONSE_BODY);
    }

    @Test
    void getResponseEncryptedWithResponseKeyEnvelopeCek() throws Exception {
        SecretKey responseCek = aes256();

        MockHttpServletRequest request = new MockHttpServletRequest("GET", "/api/orders/42");
        request.addHeader("Accept", "application/jose");
        request.addHeader("JWE-Response-Key", responseKeyEnvelope(responseCek));
        MockHttpServletResponse response = new MockHttpServletResponse();

        filter().doFilter(request, response, JSON_CONTROLLER);

        assertThat(response.getContentType()).isEqualTo(JweProtocol.APPLICATION_JOSE_VALUE);
        assertThat(decrypt(response, responseCek)).isEqualTo(RESPONSE_BODY);
    }
}
